CREATE TABLE IF NOT EXISTS "user" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(64),
    login VARCHAR(64),
    name VARCHAR(64),
    birthday timestamp
);

CREATE TABLE IF NOT EXISTS "film" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(64),
    description VARCHAR(1024),
    release_date timestamp,
    duration INTEGER,
    likes_count INTEGER
);
